// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALcSpYdLDMYNSaZ2LFgegEeW6I69Qrmnw',
    appId: '1:177506939794:web:5485acf3d0275b066d474b',
    messagingSenderId: '177506939794',
    projectId: 'crypto-analysis-793ad',
    authDomain: 'crypto-analysis-793ad.firebaseapp.com',
    storageBucket: 'crypto-analysis-793ad.firebasestorage.app',
    measurementId: 'G-038LV0H5H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCI1beFFN7n3_fyyp7nOT8sCF0U96pGbU',
    appId: '1:177506939794:android:ab8b37a4de1202716d474b',
    messagingSenderId: '177506939794',
    projectId: 'crypto-analysis-793ad',
    storageBucket: 'crypto-analysis-793ad.firebasestorage.app',
  );
}
